name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: 7.1
            phpstan-version: "1.10"
            phpunit-version: "8.5"
          - php-version: 8.4
            phpstan-version: "2.1"
            phpunit-version: "12.0"
    name: PHP ${{ matrix.php-version }} - phpstan ${{ matrix.phpstan-version }} - phpunit ${{ matrix.phpunit-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
          coverage: none

      - name: Install dependencies
        run: |
          composer update --no-interaction --prefer-dist
          composer remove phpunit/phpunit phpstan/phpstan --dev || true

          composer require --dev phpstan/phpstan:^${{ matrix.phpstan-version }} --no-interaction || true
          
          # Gán phpunit version phù hợp theo PHP
          if [[ "${{ matrix.php-version }}" == "7.1" ]]; then
            composer require --dev phpunit/phpunit:^8.5 --no-interaction
          elif [[ "${{ matrix.php-version }}" == "7.4" ]]; then
            composer require --dev phpunit/phpunit:^9.6 --no-interaction
          elif [[ "${{ matrix.php-version }}" == "8.0" ]]; then
            composer require --dev phpunit/phpunit:^9.6 --no-interaction
          else
            composer require --dev phpunit/phpunit:^${{ matrix.phpunit-version }} --no-interaction
          fi

      - name: Run PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "phpunit not installed for this combination, skipping"
          fi

      - name: Run PHPStan
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse src --level=max || true
          else
            echo "phpstan not installed for this combination, skipping"
          fi
